#!/bin/sh
#chkconfig: 2345 70 30
#description: hadoop-hdfs-ftp sevice
#processname: hadoop-hdfs-ftp   
                       
. /lib/lsb/init-functions

RETVAL_SUCCESS=0

STATUS_RUNNING=0
STATUS_DEAD=1
STATUS_DEAD_AND_LOCK=2
STATUS_NOT_RUNNING=3
STATUS_OTHER_ERROR=102

SLEEP_TIME=30
PROC_NAME="java"
PIDFILE="/var/run/hadoop-hdfs/hadoop-hdfs-ftp.pid"

EXEC_PATH="/usr/local/hdfs-ftp/hadoop-hdfs-ftp"
DAEMON="hadoop-hdfs-ftp"

CheckProcess()
{
  
  pidofproc -p $PIDFILE $PROC_NAME > /dev/null
  status=$?
  if [ $status -eq $STATUS_RUNNING ];
  then
    #echo "$DAEMON is running"
    return 0
  else
    echo "$DAEMON is dead"
    return 1
  fi
}

                           
while [ 1 ] ; do
 CheckProcess 
 Check_RET=$?
 if [ $Check_RET -eq $STATUS_DEAD ];
 then
  #restart
  echo "Restart $DAEMON..."
  $EXEC_PATH start
 fi
 sleep $SLEEP_TIME
done